-- 008c: All Quiz Questions
-- Run after 008b.


-- =============================================================================
-- QUIZ QUESTIONS (scenario-based comprehension)
-- =============================================================================

-- Module 1
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000001', 'What is your employment relationship with Sweepr?', '["A part-time employee of Sweepr", "An independent contractor using the Sweepr marketplace", "A full-time employee with benefits", "A franchise owner"]', 'An independent contractor using the Sweepr marketplace', 'Sweepr is a marketplace. All cleaners operate as independent contractors — responsible for their own taxes, insurance, and tools.', 1),
('11111111-0001-0001-0001-000000000001', 'Who is responsible for your income taxes as a Sweepr cleaner?', '["Sweepr withholds and pays them automatically", "You are responsible for your own income and self-employment taxes", "They are included in the platform fee", "Only if you earn more than $50,000"]', 'You are responsible for your own income and self-employment taxes', 'As a contractor you pay your own income and self-employment tax (15.3%). Sweepr issues a 1099-NEC but does not withhold.', 2),
('11111111-0001-0001-0001-000000000001', 'A customer gives you a 4-star review instead of 5. Why does this matter more than it seems?', '["It has no real impact", "It reduces that customer''s rebooking probability by over 60%", "It only matters for Elite cleaners", "It only affects tips"]', 'It reduces that customer''s rebooking probability by over 60%', 'A 4-star vs 5-star clean cuts rebooking probability for that customer by more than 60%. Consistency protects your income.', 3),
('11111111-0001-0001-0001-000000000001', 'What insurance must you maintain to work on Sweepr?', '["None — Sweepr covers everything", "Your own general liability insurance with at least $1M coverage", "A home warranty", "Health insurance only"]', 'Your own general liability insurance with at least $1M coverage', 'You must carry a $1M-per-occurrence general liability policy. Platform coverage is supplemental, not primary.', 4),
('11111111-0001-0001-0001-000000000001', 'How does Sweepr support your business?', '["It assigns you jobs on a fixed schedule", "It connects you with customers and handles booking, payment, and messaging", "It guarantees an hourly wage", "It provides your cleaning supplies"]', 'It connects you with customers and handles booking, payment, and messaging', 'Sweepr is a business-development partner — it handles customer acquisition, booking, payment, and dispute resolution. You provide the expertise.', 5);

-- Module 2
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000002', 'A job offer arrives. Roughly how long do you have to accept or decline?', '["1 hour", "24 hours", "15 minutes", "Until the scheduled start time"]', '15 minutes', 'Offers have a ~15-minute window before expiring to the next cleaner. Review quickly and decide.', 1),
('11111111-0001-0001-0001-000000000002', 'Where should you look up a keypad code for a job?', '["Your personal notebook", "The job detail screen in the Sweepr app", "A text from the customer", "A sticky note on your dashboard"]', 'The job detail screen in the Sweepr app', 'All entry instructions are encrypted in the app. Never store codes outside the platform.', 2),
('11111111-0001-0001-0001-000000000002', 'You finished cleaning but the app still shows the job "in progress." What happens to your pay?', '["You''re paid automatically anyway", "Payout isn''t processed until you mark the job complete", "It pays at the end of the month regardless", "The customer pays you in cash"]', 'Payout isn''t processed until you mark the job complete', 'Payouts trigger on completion. Jobs left "in progress" are not paid. Always mark complete promptly.', 3),
('11111111-0001-0001-0001-000000000002', 'Traffic will make you 20 minutes late. What is the right move?', '["Show up late and apologize in person", "Message the customer in-app before your arrival window closes", "Cancel the job", "Call support first"]', 'Message the customer in-app before your arrival window closes', 'Proactive in-app notice is the professional standard and prevents a late arrival from being logged as a no-show.', 4),
('11111111-0001-0001-0001-000000000002', 'You cancel a job 12 hours before it starts. What is the typical reliability impact?', '["No impact", "A 3-point reduction", "Immediate suspension", "Loss of tier status instantly"]', 'A 3-point reduction', 'A cancellation within 24 hours costs 3 reliability points; a no-call/no-show costs 10.', 5);

-- Module 3
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000003', 'You''re cleaning a bedroom and see prescription medications on a nightstand. A friend later asks if you noticed anything interesting. You should:', '["Share general details", "Decline to discuss any details about the customer''s home", "Mention the medications", "Describe only the home layout"]', 'Decline to discuss any details about the customer''s home', 'What you see inside a home stays inside that home. Discussing any customer details — even seemingly harmless ones — violates privacy and trust.', 1),
('11111111-0001-0001-0001-000000000003', 'A customer gives you a physical house key. What is the correct handling?', '["Make a backup copy in case you lose it", "Store it safely and return it as instructed; never copy or share it", "Leave it under the doormat for next time", "Give it to a household member"]', 'Store it safely and return it as instructed; never copy or share it', 'Keys are never copied or shared. If a key is lost, contact support and the customer immediately.', 2),
('11111111-0001-0001-0001-000000000003', 'You arrive and the front door is already open. What should you do?', '["Walk in and start cleaning", "Contact the customer before entering and document the arrival time and door state", "Call the police immediately", "Leave and mark the job incomplete"]', 'Contact the customer before entering and document the arrival time and door state', 'An open door could signal a problem. Contact the customer first; if there are signs of a break-in or you feel unsafe, don''t enter and call emergency services.', 3),
('11111111-0001-0001-0001-000000000003', 'Which of these is actually allowed inside a customer''s home?', '["Photographing the decor for social media", "Listening to music through one earbud while working", "Eating food from the fridge when hungry", "Inviting a friend to help without telling the customer"]', 'Listening to music through one earbud while working', 'One earbud is fine — the other must stay free for awareness. Photography, eating their food, and unregistered guests are all prohibited.', 4),
('11111111-0001-0001-0001-000000000003', 'When may you photograph inside a customer''s home?', '["Whenever something looks interesting", "Only to document damage or an incident, shared via the Sweepr claims system", "Before every clean for social media", "After every clean for a portfolio"]', 'Only to document damage or an incident, shared via the Sweepr claims system', 'Photography is allowed only to document damage/incidents through the claims system — never for social media or personal use.', 5);

-- Module 4
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000004', 'What is the most common reason cleaners are permanently removed?', '["Too many 4-star reviews", "Off-platform bookings — accepting cash or directing customers to book outside Sweepr", "A reliability score below 80", "Using the customer''s WiFi"]', 'Off-platform bookings — accepting cash or directing customers to book outside Sweepr', 'Off-platform booking violates the ICA and is the most enforced rule, harming customer trust and the marketplace.', 1),
('11111111-0001-0001-0001-000000000004', 'Your liability insurance lapses. What happens and what should you do?', '["Nothing — platform insurance covers you", "You''re suspended from new offers until you upload a current certificate", "You verbally tell customers you''re uninsured", "You must cancel your account"]', 'You''re suspended from new offers until you upload a current certificate', 'Active insurance is required. A lapse suspends new offers until a valid certificate is on file.', 2),
('11111111-0001-0001-0001-000000000004', 'A customer asks for your personal number so they can book you directly next time. You should:', '["Give it — direct relationships are good business", "Politely decline and explain all communication must stay on the platform", "Give a fake number", "Report the customer to support"]', 'Politely decline and explain all communication must stay on the platform', 'Giving contact info for direct booking is prohibited off-platform solicitation. Decline politely and explain the platform requirement.', 3),
('11111111-0001-0001-0001-000000000004', 'Under the contractor model, who controls how you perform the cleaning?', '["Sweepr dictates every step", "You control your methods; Sweepr sets the quality standard and scope, not the process", "The customer dictates every step you must follow", "Your insurer"]', 'You control your methods; Sweepr sets the quality standard and scope, not the process', 'Contractor status means you decide how to achieve the required outcome. Sweepr defines what, not how.', 4),
('11111111-0001-0001-0001-000000000004', 'A customer asks you to delete their personal information from your records. You should:', '["Delete your own notes and contacts", "Direct them to Sweepr''s privacy team and not fulfill the request yourself", "Tell them you have no records", "Email them your records"]', 'Direct them to Sweepr''s privacy team and not fulfill the request yourself', 'CCPA/GDPR deletion requests must be handled by Sweepr''s privacy team, not individual contractors.', 5),
('11111111-0001-0001-0001-000000000004', 'When does Sweepr''s supplemental insurance apply?', '["To any damage during any job", "To verified incidents during booked jobs after your own insurance has paid out", "Only when you have no insurance", "To damage you cause intentionally"]', 'To verified incidents during booked jobs after your own insurance has paid out', 'Platform coverage is secondary — it activates only after your policy is exhausted, and never for negligence or intentional acts.', 6);

-- Module 5
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000005', 'Which combination produces toxic chloramine gas?', '["Bleach and dish soap", "Bleach and ammonia-based cleaners", "Vinegar and baking soda", "Hydrogen peroxide and water"]', 'Bleach and ammonia-based cleaners', 'Bleach + ammonia creates toxic chloramine gas — one of the most dangerous mixing errors. Never combine them.', 1),
('11111111-0001-0001-0001-000000000005', 'What is the minimum PPE for standard cleaning?', '["None required", "Nitrile or latex gloves and eye protection when using sprays", "A full hazmat suit", "Only a face mask"]', 'Nitrile or latex gloves and eye protection when using sprays', 'Minimum is nitrile/latex gloves (not vinyl) and eye protection for sprays or overhead work. Stronger chemicals require more.', 2),
('11111111-0001-0001-0001-000000000005', 'A tile bathroom has colored grout. Why avoid bleach?', '["It doesn''t clean grout", "Bleach fades colored grout; use oxygen-based cleaners instead", "Bleach is too expensive", "Grout doesn''t need cleaning"]', 'Bleach fades colored grout; use oxygen-based cleaners instead', 'Bleach permanently strips color from grout. Oxygen-based cleaners are safe and effective.', 3),
('11111111-0001-0001-0001-000000000005', 'You need to move a heavy sofa to clean under it. The safe technique is:', '["Bend at the waist and use your back", "Lift with your legs, keep the load close, avoid twisting", "Always ask the customer to help", "Never move any furniture"]', 'Lift with your legs, keep the load close, avoid twisting', 'Legs bent, back straight, load close, no twisting prevents the back and knee injuries common in cleaning.', 4),
('11111111-0001-0001-0001-000000000005', 'A fire breaks out while you''re cleaning. Your first action is:', '["Put it out with water", "Evacuate safely and call 911; leave your equipment", "Call Sweepr support before 911", "Finish your current task, then evacuate"]', 'Evacuate safely and call 911; leave your equipment', 'Life safety comes first. Evacuate, call 911, then notify Sweepr. Never fight a fire — your equipment is replaceable.', 5),
('11111111-0001-0001-0001-000000000005', 'What does "dwell time" mean?', '["Time spent in each room", "The time you let a product sit before wiping, which improves effectiveness", "Time between visits", "A product''s expiration date"]', 'The time you let a product sit before wiping, which improves effectiveness', 'Dwell time lets the product break down grime before you wipe. Skipping it means wiping, not cleaning.', 6);

-- Module 6
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000006', 'What is the recommended room sequence?', '["Entryway first, bedrooms last", "Bedrooms, bathrooms, kitchen, living areas, entryways", "Kitchen first, then everything else", "Whatever is fastest"]', 'Bedrooms, bathrooms, kitchen, living areas, entryways', 'This sequence prioritizes time-intensive and sanitation-critical rooms and prevents re-dirtying completed areas.', 1),
('11111111-0001-0001-0001-000000000006', 'Which direction should you work within a room?', '["Bottom to top, right to left", "Top to bottom, left to right, away from the door", "Biggest surfaces first", "Whatever feels comfortable"]', 'Top to bottom, left to right, away from the door', 'Top-to-bottom catches falling dust; left-to-right ensures coverage; away from the door avoids walking on clean floors.', 2),
('11111111-0001-0001-0001-000000000006', 'For streak-free mirrors and glass, you should use:', '["Paper towels with cleaner", "A dedicated microfiber cloth with cleaner applied to the cloth, not the glass", "Any rag with soap and water", "Newspaper"]', 'A dedicated microfiber cloth with cleaner applied to the cloth, not the glass', 'Paper towels leave lint. Apply cleaner to the cloth to avoid overspray, and use a dedicated glass cloth.', 3),
('11111111-0001-0001-0001-000000000006', 'A customer has a marble countertop. Which cleaner is safe?', '["All-purpose cleaner with bleach", "pH-neutral stone cleaner only", "Vinegar-based cleaner", "Abrasive scrubbing powder"]', 'pH-neutral stone cleaner only', 'Marble is acid-sensitive; acidic or abrasive products etch it permanently. Use only pH-neutral stone cleaners.', 4),
('11111111-0001-0001-0001-000000000006', 'When should you use the in-app checklist?', '["Only at the end to confirm", "As you go, checking items off when complete", "Once a week in a batch", "Only for deep cleans"]', 'As you go, checking items off when complete', 'Checking off as you go forces systematic coverage. Doing it from memory afterward is unreliable.', 5),
('11111111-0001-0001-0001-000000000006', 'The most effective way to prevent quality failures is:', '["Clean as fast as possible", "Use the checklist in real time and do a final customer-perspective walkthrough", "Ask the customer to point out spots", "Clean only what''s specifically requested"]', 'Use the checklist in real time and do a final customer-perspective walkthrough', 'Checklist discipline plus a customer''s-eye final walkthrough catches missed areas before the customer does.', 6);

-- Module 7
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000007', 'Why should all job communication stay in the Sweepr app?', '["It''s required and creates a documented, timestamped record", "It''s faster than texting", "So Sweepr can read your messages", "It''s optional"]', 'It''s required and creates a documented, timestamped record', 'In-app messages are timestamped and usable in disputes. Off-platform messages have no evidentiary value to Sweepr.', 1),
('11111111-0001-0001-0001-000000000007', 'You realize a job will run long. When should you tell the customer?', '["At the very end when you''re not done", "At the halfway point, proactively", "After you finish, in the wrap-up", "Never — just hurry"]', 'At the halfway point, proactively', 'Halfway notice gives maximum warning and frames the overrun as thoroughness rather than a surprise.', 2),
('11111111-0001-0001-0001-000000000007', 'A customer messages that they''re unhappy with the clean. Best first response?', '["Explain why you did everything correctly", "Listen, acknowledge their concern, and offer to make it right", "Offer a direct refund", "Ignore it"]', 'Listen, acknowledge their concern, and offer to make it right', 'Acknowledgment de-escalates. "I understand and want to make this right" beats justification. Then offer a solution.', 3),
('11111111-0001-0001-0001-000000000007', 'Which is allowed in your in-app messages?', '["Asking for a 5-star review", "A brief professional completion summary", "Negative comments about other cleaners", "Offering future work off-platform at a discount"]', 'A brief professional completion summary', 'A completion summary builds goodwill. Soliciting reviews, disparaging others, and off-platform offers are all prohibited.', 4),
('11111111-0001-0001-0001-000000000007', 'When should you escalate to Sweepr support instead of handling it yourself?', '["When you get a 4-star review", "When a customer is abusive, changes payment terms, or requests out-of-scope work", "Whenever you disagree", "Never"]', 'When a customer is abusive, changes payment terms, or requests out-of-scope work', 'Abuse, payment manipulation, unsafe conditions, and out-of-scope requests exceed a contractor''s role — escalate.', 5);

-- Module 8
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000008', 'The single most important preventive measure against damage claims is:', '["Work slowly", "Photograph pre-existing damage before cleaning each room", "Use only the customer''s products", "Never move furniture"]', 'Photograph pre-existing damage before cleaning each room', 'A timestamped pre-clean photo is your primary defense against false claims. Without it, you have no proof.', 1),
('11111111-0001-0001-0001-000000000008', 'You accidentally break a ceramic vase. What do you do first?', '["Clean up the pieces and hope it goes unnoticed", "Photograph it, message the customer in-app, and file a report within an hour", "Try to glue it", "Mention it verbally at the end"]', 'Photograph it, message the customer in-app, and file a report within an hour', 'Prompt, honest reporting is both ethical and practical. Hiding damage means removal when discovered.', 2),
('11111111-0001-0001-0001-000000000008', 'A customer claims you damaged something you know was already broken. You should:', '["Accept responsibility to keep them happy", "Respond through the claims interface with your dated pre-job photos and facts", "Accuse the customer of lying", "Ignore the claim"]', 'Respond through the claims interface with your dated pre-job photos and facts', 'Present documentation factually without accusation. The trust team reviews both accounts and photo metadata.', 3),
('11111111-0001-0001-0001-000000000008', 'During put-away, how many glasses should you carry at once?', '["As many as possible", "2–3 at a time, held by the body not the rim", "At least 10 to save time", "Stack them all in one trip"]', '2–3 at a time, held by the body not the rim', 'Breakage risk rises with overloaded carries. Extra trips are cheaper than a broken item.', 4),
('11111111-0001-0001-0001-000000000008', 'During an open damage claim, how quickly must you respond to information requests?', '["7 days", "1 month", "Within 48 hours", "You never need to respond"]', 'Within 48 hours', 'Respond within 48 hours during an active claim. Non-responsive cleaners may be suspended pending resolution.', 5);

-- Module 9
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000009', 'How are recent reviews weighted in your quality score?', '["All reviews count equally", "Reviews from the past 30 days count 2x vs. older ones", "Older reviews count more", "Only the last 5 matter"]', 'Reviews from the past 30 days count 2x vs. older ones', 'Recent performance is weighted double, so consistent recent quality recovers your score faster.', 1),
('11111111-0001-0001-0001-000000000009', 'What does Preferred tier require?', '["Quality above 4.0 and reliability above 70", "Quality above 4.5, reliability above 85, and 20+ jobs in 90 days", "Quality above 4.8 and 40+ jobs/month", "Just finishing training"]', 'Quality above 4.5, reliability above 85, and 20+ jobs in 90 days', 'Preferred needs 4.5+ quality, 85+ reliability, and 20+ completed jobs in 90 days. Elite is stricter.', 2),
('11111111-0001-0001-0001-000000000009', 'How much does a no-call/no-show reduce your reliability score?', '["1 point", "3 points", "10 points", "Immediate suspension"]', '10 points', 'A no-call/no-show costs 10 points — far more than a 24-hour cancellation (3 points).', 3),
('11111111-0001-0001-0001-000000000009', 'A family emergency causes you to miss a job. What should you do?', '["Nothing — emergencies are excused automatically", "Contact support within 24 hours, document it, and request a hardship review", "Enter a fake cancellation reason", "Delete your account"]', 'Contact support within 24 hours, document it, and request a hardship review', 'Hardship provisions exist for documented emergencies. Contact support within 24 hours; the impact may be reduced.', 4),
('11111111-0001-0001-0001-000000000009', 'You receive a rating you believe is unfair. What''s the rule on disputes?', '["Dispute anytime you disagree", "Dispute within 7 days when you believe a rating is unfair or inaccurate", "All ratings are final", "Only Elite cleaners can dispute"]', 'Dispute within 7 days when you believe a rating is unfair or inaccurate', 'You have 7 days to dispute. Valid errors may be removed; gaming the system with bad-faith disputes earns warnings.', 5);

-- Module 10
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000010', 'The app crashes mid-job. What most likely happened to your progress?', '["It''s lost permanently", "It''s saved server-side and reloads when you reopen the app", "You must restart the whole job", "You need to rebook with the customer"]', 'It''s saved server-side and reloads when you reopen the app', 'Progress is saved server-side in real time. A crash just disconnects the client; reopening reconnects your session.', 1),
('11111111-0001-0001-0001-000000000010', 'A payout is 3 business days late beyond the 7-day window. You should:', '["Wait another week", "Contact support through the Help tab with the specific job IDs", "Contact the customer for payment", "File a bank chargeback"]', 'Contact support through the Help tab with the specific job IDs', 'Small delays are normal; at 3+ days late, contact support with job IDs. Never involve the customer in payment issues.', 2),
('11111111-0001-0001-0001-000000000010', 'You can''t access the property and the customer won''t answer. Fastest help is:', '["Email support@sweepr.com", "Post on social media", "The in-app emergency contact, which escalates to a senior agent", "Conference the customer into a support call"]', 'The in-app emergency contact, which escalates to a senior agent', 'The in-app emergency option bypasses the queue for active-job situations and reaches a senior agent fast.', 3),
('11111111-0001-0001-0001-000000000010', 'How should you write a support request for the fastest resolution?', '["Describe it vaguely and let support figure it out", "Include the job ID, the exact issue, what you tried, and screenshots", "Just say the app isn''t working", "Submit several tickets for the same issue"]', 'Include the job ID, the exact issue, what you tried, and screenshots', 'Complete first-message detail eliminates back-and-forth and lets support resolve it immediately.', 4),
('11111111-0001-0001-0001-000000000010', 'Your battery is dying and you didn''t save the address. Best option?', '["Cancel the job", "Use the offline-cached job details in the app, or a screenshot taken before departing", "Call a friend to look it up", "Ring nearby doorbells"]', 'Use the offline-cached job details in the app, or a screenshot taken before departing', 'The app caches addresses offline. Screenshotting before leaving is the recommended backup.', 5);

-- Standard Cleaning quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000001', 'What does a standard clean guarantee that a deep clean is defined by going beyond?', '["Consistent, thorough surface maintenance every visit", "Cleaning inside appliances every visit", "Full cabinet-interior cleaning", "Wall and ceiling cleaning"]', 'Consistent, thorough surface maintenance every visit', 'Standard cleans are maintenance cleans — thorough surface work done consistently. Deep cleaning adds the intensive areas.', 1),
('22222222-0002-0002-0002-000000000001', 'You finish a standard clean well ahead of schedule. What should you do?', '["Leave early and mark complete", "Use the time for finishing touches that drive 5-star reviews", "Start a different job", "Bill for extra time anyway"]', 'Use the time for finishing touches that drive 5-star reviews', 'Spare time is an opportunity for details that earn 5 stars. Never leave early just to pad your rate.', 2),
('22222222-0002-0002-0002-000000000001', 'A customer expects inside-oven cleaning on a standard clean. You should:', '["Do it for free to avoid conflict", "Explain that''s a deep-clean item and offer to prioritize what''s in scope", "Refuse and end the job", "Ignore the request"]', 'Explain that''s a deep-clean item and offer to prioritize what''s in scope', 'Inside appliances are deep-clean scope. Kindly clarify scope and offer to prioritize in-scope work.', 3);

-- Deep Cleaning quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000002', 'How much extra time should you budget for a deep clean vs. a standard clean of the same home?', '["The same amount", "50–75% more", "Always twice as long", "It depends only on bathrooms"]', '50–75% more', 'Deep cleans need 50–75% more time; very neglected homes need even more. Flag scope concerns before starting.', 1),
('22222222-0002-0002-0002-000000000002', 'What should you do with refrigerator shelves and drawers during a deep clean?', '["Wipe them in place", "Remove them, wash in the sink, dry thoroughly, then replace", "Leave them and clean around", "Clean them with oven cleaner"]', 'Remove them, wash in the sink, dry thoroughly, then replace', 'Removing allows complete interior cleaning. Wash with dish soap, dry fully to prevent moisture, and replace.', 2),
('22222222-0002-0002-0002-000000000002', 'Which cleaner is safe for colored grout?', '["Chlorine bleach", "Oxygen-based cleaner like OxiClean", "Any all-purpose cleaner", "Acid-based tile cleaner"]', 'Oxygen-based cleaner like OxiClean', 'Bleach fades grout and acids damage it. Oxygen-based cleaners are safe and effective on most grout.', 3);

-- Move-In/Out quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000003', 'Why is documentation especially important for move-out cleans?', '["To show off your work", "They occur at transition points where landlord-tenant disputes are common and photos may be requested as evidence", "It''s legally required for move-outs", "To help the next cleaner"]', 'They occur at transition points where landlord-tenant disputes are common and photos may be requested as evidence', 'Deposits are at stake. Before/after photos protect you and may be requested in a dispute.', 1),
('22222222-0002-0002-0002-000000000003', 'You find suspected mold in a bathroom during a move-out clean. What should you do?', '["Clean it with bleach and continue", "Stop work on that area, photograph it, and message the customer", "Ignore it and clean around it", "Call the health department"]', 'Stop work on that area, photograph it, and message the customer', 'Mold remediation is outside cleaning scope. Stop, document, and notify the customer — don''t attempt to clean it.', 2),
('22222222-0002-0002-0002-000000000003', 'A landlord is present and asks your opinion on the tenant''s deposit. You should:', '["Share your honest opinion of the home''s condition", "Stay focused on cleaning and avoid discussing the dispute", "Tell them everything you noticed", "Ask the landlord to leave"]', 'Stay focused on cleaning and avoid discussing the dispute', 'Your role is to clean, not testify. Statements could be misrepresented in a landlord-tenant dispute.', 3);

-- Pet Homes quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000004', 'Which product actually eliminates pet odors rather than masking them?', '["Air freshener spray", "Scented candles", "Enzyme-based cleaner", "Baking soda only"]', 'Enzyme-based cleaner', 'Enzyme cleaners break down organic odor compounds. Fresheners and candles only mask odors temporarily.', 1),
('22222222-0002-0002-0002-000000000004', 'Why avoid strong bleach products where pets walk?', '["It damages flooring", "Residual bleach is toxic to dogs and cats", "It doesn''t clean pet areas", "It''s too expensive"]', 'Residual bleach is toxic to dogs and cats', 'Pets lick their paws after walking on treated surfaces; residual bleach can seriously harm them. Use pet-safe products.', 2),
('22222222-0002-0002-0002-000000000004', 'A dog is growling and snapping at you mid-job. What should you do?', '["Calm it with treats", "Stop work, contact the customer, and wait for guidance", "Continue in another room", "Leave without notifying anyone"]', 'Stop work, contact the customer, and wait for guidance', 'An aggressive pet is a safety hazard. Stop, don''t handle the animal, and contact the customer for guidance.', 3);

-- Laundry quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000005', 'When should you start the laundry during a visit?', '["After all cleaning is done", "At the beginning, so it runs while you clean", "Only when asked", "Order doesn''t matter"]', 'At the beginning, so it runs while you clean', 'Starting early maximizes efficiency — cycles run while you do other tasks and you finish put-away near the end.', 1),
('22222222-0002-0002-0002-000000000005', 'You find what looks like a silk blouse in the pile. What should you do?', '["Wash gentle/cold", "Set it aside and note it — it may need special handling or dry cleaning", "Wash normal/warm", "Dry on high heat"]', 'Set it aside and note it — it may need special handling or dry cleaning', 'Silk, wool, and delicates shouldn''t be washed without guidance. Set aside and communicate; damage is costly.', 2),
('22222222-0002-0002-0002-000000000005', 'No instructions are provided. What default water temperature for darks?', '["Hot", "Warm", "Cold — prevents color bleeding and shrinkage", "Any temperature"]', 'Cold — prevents color bleeding and shrinkage', 'Cold is the safe default for darks. When in doubt, cooler water is safer.', 3);

-- Dishes quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000006', 'There are crystal wine glasses in the dish pile. What should you do?', '["Dishwasher on gentle", "Hand-wash carefully and dry immediately with a clean cloth", "Skip them entirely", "Scrub hard with a sponge"]', 'Hand-wash carefully and dry immediately with a clean cloth', 'Crystal should always be hand-washed; dishwasher heat and detergent can cloud or crack it over time.', 1),
('22222222-0002-0002-0002-000000000006', 'You break a plate during the dishes add-on. Correct procedure?', '["Throw away the pieces quietly", "Photograph it, message the customer in-app, and file a damage report", "Buy a replacement yourself", "Mention it verbally at the end"]', 'Photograph it, message the customer in-app, and file a damage report', 'Damage reporting is the same for add-ons: document, notify in-app, and file a report.', 2),
('22222222-0002-0002-0002-000000000006', 'You can''t tell where a specific pot belongs. What should you do?', '["Guess the most logical cabinet", "Set it on the counter and note its location in your completion message", "Put it in a random drawer", "Leave it in the drying rack"]', 'Set it on the counter and note its location in your completion message', 'When unsure, leave it visible and communicate. Wrong placement is more disruptive than a noted counter item.', 3);

-- Interior Windows quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000007', 'How should glass cleaner be applied for streak-free results?', '["Sprayed directly on the glass", "Applied to the microfiber cloth, then to the glass", "Sprayed on the squeegee blade", "Applied to paper towels"]', 'Applied to the microfiber cloth, then to the glass', 'Spraying the cloth avoids overspray on frames, sills, and electronics and gives better product control.', 1),
('22222222-0002-0002-0002-000000000007', 'A floor-to-ceiling window needs cleaning but you didn''t bring an extension squeegee. What should you do?', '["Climb on the windowsill", "Document the inaccessible areas and offer to return with proper equipment", "Skip it without noting", "Stand on the customer''s chair"]', 'Document the inaccessible areas and offer to return with proper equipment', 'Never improvise unstable platforms. Document what couldn''t be safely reached and offer a return visit.', 2),
('22222222-0002-0002-0002-000000000007', 'How do you best check windows for streaks?', '["Wipe once more for safety", "View from an angle in natural light", "Run a finger along the glass", "Look head-on under overhead lighting"]', 'View from an angle in natural light', 'A raking angle in natural light reveals streaks that head-on viewing misses.', 3);

-- Organization quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000008', 'You booked a pantry organization, but the bedroom closet is also a mess. What should you do?', '["Organize the closet as a bonus", "Stick to the pantry; note the closet for a possible future booking", "Add the closet to the bill yourself", "Do the closet instead of the pantry"]', 'Stick to the pantry; note the closet for a possible future booking', 'Only organize what''s booked. Touching unrequested areas can hide items. Note opportunities for the future.', 1),
('22222222-0002-0002-0002-000000000008', 'While organizing a pantry you find what looks like trash. What should you do?', '["Throw it away", "Leave it; only discard with explicit customer permission", "Bag it by the front door", "Decide based on your judgment"]', 'Leave it; only discard with explicit customer permission', 'Never discard items without permission — apparent trash may matter to the customer. You organize, you don''t decide.', 2),
('22222222-0002-0002-0002-000000000008', 'A customer asks for organization suggestions. Your role is to:', '["Impose your own system", "Offer options and implement what the customer chooses", "Decline to suggest anything", "Follow a fixed method regardless"]', 'Offer options and implement what the customer chooses', 'You assist the customer''s vision. Offer professional options, then implement their decision — their system is the right one.', 3);
