
-- =============================================================================
-- QUIZ QUESTIONS (scenario-based comprehension)
-- =============================================================================

-- Module 1
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000001', 'What is your employment relationship with Sweepr?', '["A part-time employee of Sweepr", "An independent contractor using the Sweepr marketplace", "A full-time employee with benefits", "A franchise owner"]', 'An independent contractor using the Sweepr marketplace', 'Sweepr is a marketplace. All cleaners operate as independent contractors — responsible for their own taxes, insurance, and tools.', 1),
('11111111-0001-0001-0001-000000000001', 'Who is responsible for your income taxes as a Sweepr cleaner?', '["Sweepr withholds and pays them automatically", "You are responsible for your own income and self-employment taxes", "They are included in the platform fee", "Only if you earn more than $50,000"]', 'You are responsible for your own income and self-employment taxes', 'As a contractor you pay your own income and self-employment tax (15.3%). Sweepr issues a 1099-NEC but does not withhold.', 2),
('11111111-0001-0001-0001-000000000001', 'A customer gives you a 4-star review instead of 5. Why does this matter more than it seems?', '["It has no real impact", "It reduces that customer''s rebooking probability by over 60%", "It only matters for Elite cleaners", "It only affects tips"]', 'It reduces that customer''s rebooking probability by over 60%', 'A 4-star vs 5-star clean cuts rebooking probability for that customer by more than 60%. Consistency protects your income.', 3),
('11111111-0001-0001-0001-000000000001', 'What insurance must you maintain to work on Sweepr?', '["None — Sweepr covers everything", "Your own general liability insurance with at least $1M coverage", "A home warranty", "Health insurance only"]', 'Your own general liability insurance with at least $1M coverage', 'You must carry a $1M-per-occurrence general liability policy. Platform coverage is supplemental, not primary.', 4),
('11111111-0001-0001-0001-000000000001', 'How does Sweepr support your business?', '["It assigns you jobs on a fixed schedule", "It connects you with customers and handles booking, payment, and messaging", "It guarantees an hourly wage", "It provides your cleaning supplies"]', 'It connects you with customers and handles booking, payment, and messaging', 'Sweepr is a business-development partner — it handles customer acquisition, booking, payment, and dispute resolution. You provide the expertise.', 5);

-- Module 2
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000002', 'A job offer arrives. Roughly how long do you have to accept or decline?', '["1 hour", "24 hours", "15 minutes", "Until the scheduled start time"]', '15 minutes', 'Offers have a ~15-minute window before expiring to the next cleaner. Review quickly and decide.', 1),
('11111111-0001-0001-0001-000000000002', 'Where should you look up a keypad code for a job?', '["Your personal notebook", "The job detail screen in the Sweepr app", "A text from the customer", "A sticky note on your dashboard"]', 'The job detail screen in the Sweepr app', 'All entry instructions are encrypted in the app. Never store codes outside the platform.', 2),
('11111111-0001-0001-0001-000000000002', 'You finished cleaning but the app still shows the job "in progress." What happens to your pay?', '["You''re paid automatically anyway", "Payout isn''t processed until you mark the job complete", "It pays at the end of the month regardless", "The customer pays you in cash"]', 'Payout isn''t processed until you mark the job complete', 'Payouts trigger on completion. Jobs left "in progress" are not paid. Always mark complete promptly.', 3),
('11111111-0001-0001-0001-000000000002', 'Traffic will make you 20 minutes late. What is the right move?', '["Show up late and apologize in person", "Message the customer in-app before your arrival window closes", "Cancel the job", "Call support first"]', 'Message the customer in-app before your arrival window closes', 'Proactive in-app notice is the professional standard and prevents a late arrival from being logged as a no-show.', 4),
('11111111-0001-0001-0001-000000000002', 'You cancel a job 12 hours before it starts. What is the typical reliability impact?', '["No impact", "A 3-point reduction", "Immediate suspension", "Loss of tier status instantly"]', 'A 3-point reduction', 'A cancellation within 24 hours costs 3 reliability points; a no-call/no-show costs 10.', 5);

-- Module 3
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000003', 'You''re cleaning a bedroom and see prescription medications on a nightstand. A friend later asks if you noticed anything interesting. You should:', '["Share general details", "Decline to discuss any details about the customer''s home", "Mention the medications", "Describe only the home layout"]', 'Decline to discuss any details about the customer''s home', 'What you see inside a home stays inside that home. Discussing any customer details — even seemingly harmless ones — violates privacy and trust.', 1),
('11111111-0001-0001-0001-000000000003', 'A customer gives you a physical house key. What is the correct handling?', '["Make a backup copy in case you lose it", "Store it safely and return it as instructed; never copy or share it", "Leave it under the doormat for next time", "Give it to a household member"]', 'Store it safely and return it as instructed; never copy or share it', 'Keys are never copied or shared. If a key is lost, contact support and the customer immediately.', 2),
('11111111-0001-0001-0001-000000000003', 'You arrive and the front door is already open. What should you do?', '["Walk in and start cleaning", "Contact the customer before entering and document the arrival time and door state", "Call the police immediately", "Leave and mark the job incomplete"]', 'Contact the customer before entering and document the arrival time and door state', 'An open door could signal a problem. Contact the customer first; if there are signs of a break-in or you feel unsafe, don''t enter and call emergency services.', 3),
('11111111-0001-0001-0001-000000000003', 'Which of these is actually allowed inside a customer''s home?', '["Photographing the decor for social media", "Listening to music through one earbud while working", "Eating food from the fridge when hungry", "Inviting a friend to help without telling the customer"]', 'Listening to music through one earbud while working', 'One earbud is fine — the other must stay free for awareness. Photography, eating their food, and unregistered guests are all prohibited.', 4),
('11111111-0001-0001-0001-000000000003', 'When may you photograph inside a customer''s home?', '["Whenever something looks interesting", "Only to document damage or an incident, shared via the Sweepr claims system", "Before every clean for social media", "After every clean for a portfolio"]', 'Only to document damage or an incident, shared via the Sweepr claims system', 'Photography is allowed only to document damage/incidents through the claims system — never for social media or personal use.', 5);

-- Module 4
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000004', 'What is the most common reason cleaners are permanently removed?', '["Too many 4-star reviews", "Off-platform bookings — accepting cash or directing customers to book outside Sweepr", "A reliability score below 80", "Using the customer''s WiFi"]', 'Off-platform bookings — accepting cash or directing customers to book outside Sweepr', 'Off-platform booking violates the ICA and is the most enforced rule, harming customer trust and the marketplace.', 1),
('11111111-0001-0001-0001-000000000004', 'Your liability insurance lapses. What happens and what should you do?', '["Nothing — platform insurance covers you", "You''re suspended from new offers until you upload a current certificate", "You verbally tell customers you''re uninsured", "You must cancel your account"]', 'You''re suspended from new offers until you upload a current certificate', 'Active insurance is required. A lapse suspends new offers until a valid certificate is on file.', 2),
('11111111-0001-0001-0001-000000000004', 'A customer asks for your personal number so they can book you directly next time. You should:', '["Give it — direct relationships are good business", "Politely decline and explain all communication must stay on the platform", "Give a fake number", "Report the customer to support"]', 'Politely decline and explain all communication must stay on the platform', 'Giving contact info for direct booking is prohibited off-platform solicitation. Decline politely and explain the platform requirement.', 3),
('11111111-0001-0001-0001-000000000004', 'Under the contractor model, who controls how you perform the cleaning?', '["Sweepr dictates every step", "You control your methods; Sweepr sets the quality standard and scope, not the process", "The customer dictates every step you must follow", "Your insurer"]', 'You control your methods; Sweepr sets the quality standard and scope, not the process', 'Contractor status means you decide how to achieve the required outcome. Sweepr defines what, not how.', 4),
('11111111-0001-0001-0001-000000000004', 'A customer asks you to delete their personal information from your records. You should:', '["Delete your own notes and contacts", "Direct them to Sweepr''s privacy team and not fulfill the request yourself", "Tell them you have no records", "Email them your records"]', 'Direct them to Sweepr''s privacy team and not fulfill the request yourself', 'CCPA/GDPR deletion requests must be handled by Sweepr''s privacy team, not individual contractors.', 5),
('11111111-0001-0001-0001-000000000004', 'When does Sweepr''s supplemental insurance apply?', '["To any damage during any job", "To verified incidents during booked jobs after your own insurance has paid out", "Only when you have no insurance", "To damage you cause intentionally"]', 'To verified incidents during booked jobs after your own insurance has paid out', 'Platform coverage is secondary — it activates only after your policy is exhausted, and never for negligence or intentional acts.', 6);

-- Module 5
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000005', 'Which combination produces toxic chloramine gas?', '["Bleach and dish soap", "Bleach and ammonia-based cleaners", "Vinegar and baking soda", "Hydrogen peroxide and water"]', 'Bleach and ammonia-based cleaners', 'Bleach + ammonia creates toxic chloramine gas — one of the most dangerous mixing errors. Never combine them.', 1),
('11111111-0001-0001-0001-000000000005', 'What is the minimum PPE for standard cleaning?', '["None required", "Nitrile or latex gloves and eye protection when using sprays", "A full hazmat suit", "Only a face mask"]', 'Nitrile or latex gloves and eye protection when using sprays', 'Minimum is nitrile/latex gloves (not vinyl) and eye protection for sprays or overhead work. Stronger chemicals require more.', 2),
('11111111-0001-0001-0001-000000000005', 'A tile bathroom has colored grout. Why avoid bleach?', '["It doesn''t clean grout", "Bleach fades colored grout; use oxygen-based cleaners instead", "Bleach is too expensive", "Grout doesn''t need cleaning"]', 'Bleach fades colored grout; use oxygen-based cleaners instead', 'Bleach permanently strips color from grout. Oxygen-based cleaners are safe and effective.', 3),
('11111111-0001-0001-0001-000000000005', 'You need to move a heavy sofa to clean under it. The safe technique is:', '["Bend at the waist and use your back", "Lift with your legs, keep the load close, avoid twisting", "Always ask the customer to help", "Never move any furniture"]', 'Lift with your legs, keep the load close, avoid twisting', 'Legs bent, back straight, load close, no twisting prevents the back and knee injuries common in cleaning.', 4),
('11111111-0001-0001-0001-000000000005', 'A fire breaks out while you''re cleaning. Your first action is:', '["Put it out with water", "Evacuate safely and call 911; leave your equipment", "Call Sweepr support before 911", "Finish your current task, then evacuate"]', 'Evacuate safely and call 911; leave your equipment', 'Life safety comes first. Evacuate, call 911, then notify Sweepr. Never fight a fire — your equipment is replaceable.', 5),
('11111111-0001-0001-0001-000000000005', 'What does "dwell time" mean?', '["Time spent in each room", "The time you let a product sit before wiping, which improves effectiveness", "Time between visits", "A product''s expiration date"]', 'The time you let a product sit before wiping, which improves effectiveness', 'Dwell time lets the product break down grime before you wipe. Skipping it means wiping, not cleaning.', 6);

-- Module 6
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000006', 'What is the recommended room sequence?', '["Entryway first, bedrooms last", "Bedrooms, bathrooms, kitchen, living areas, entryways", "Kitchen first, then everything else", "Whatever is fastest"]', 'Bedrooms, bathrooms, kitchen, living areas, entryways', 'This sequence prioritizes time-intensive and sanitation-critical rooms and prevents re-dirtying completed areas.', 1),
('11111111-0001-0001-0001-000000000006', 'Which direction should you work within a room?', '["Bottom to top, right to left", "Top to bottom, left to right, away from the door", "Biggest surfaces first", "Whatever feels comfortable"]', 'Top to bottom, left to right, away from the door', 'Top-to-bottom catches falling dust; left-to-right ensures coverage; away from the door avoids walking on clean floors.', 2),
('11111111-0001-0001-0001-000000000006', 'For streak-free mirrors and glass, you should use:', '["Paper towels with cleaner", "A dedicated microfiber cloth with cleaner applied to the cloth, not the glass", "Any rag with soap and water", "Newspaper"]', 'A dedicated microfiber cloth with cleaner applied to the cloth, not the glass', 'Paper towels leave lint. Apply cleaner to the cloth to avoid overspray, and use a dedicated glass cloth.', 3),
('11111111-0001-0001-0001-000000000006', 'A customer has a marble countertop. Which cleaner is safe?', '["All-purpose cleaner with bleach", "pH-neutral stone cleaner only", "Vinegar-based cleaner", "Abrasive scrubbing powder"]', 'pH-neutral stone cleaner only', 'Marble is acid-sensitive; acidic or abrasive products etch it permanently. Use only pH-neutral stone cleaners.', 4),
('11111111-0001-0001-0001-000000000006', 'When should you use the in-app checklist?', '["Only at the end to confirm", "As you go, checking items off when complete", "Once a week in a batch", "Only for deep cleans"]', 'As you go, checking items off when complete', 'Checking off as you go forces systematic coverage. Doing it from memory afterward is unreliable.', 5),
('11111111-0001-0001-0001-000000000006', 'The most effective way to prevent quality failures is:', '["Clean as fast as possible", "Use the checklist in real time and do a final customer-perspective walkthrough", "Ask the customer to point out spots", "Clean only what''s specifically requested"]', 'Use the checklist in real time and do a final customer-perspective walkthrough', 'Checklist discipline plus a customer''s-eye final walkthrough catches missed areas before the customer does.', 6);
