
-- Module 7
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000007', 'Why should all job communication stay in the Sweepr app?', '["It''s required and creates a documented, timestamped record", "It''s faster than texting", "So Sweepr can read your messages", "It''s optional"]', 'It''s required and creates a documented, timestamped record', 'In-app messages are timestamped and usable in disputes. Off-platform messages have no evidentiary value to Sweepr.', 1),
('11111111-0001-0001-0001-000000000007', 'You realize a job will run long. When should you tell the customer?', '["At the very end when you''re not done", "At the halfway point, proactively", "After you finish, in the wrap-up", "Never — just hurry"]', 'At the halfway point, proactively', 'Halfway notice gives maximum warning and frames the overrun as thoroughness rather than a surprise.', 2),
('11111111-0001-0001-0001-000000000007', 'A customer messages that they''re unhappy with the clean. Best first response?', '["Explain why you did everything correctly", "Listen, acknowledge their concern, and offer to make it right", "Offer a direct refund", "Ignore it"]', 'Listen, acknowledge their concern, and offer to make it right', 'Acknowledgment de-escalates. "I understand and want to make this right" beats justification. Then offer a solution.', 3),
('11111111-0001-0001-0001-000000000007', 'Which is allowed in your in-app messages?', '["Asking for a 5-star review", "A brief professional completion summary", "Negative comments about other cleaners", "Offering future work off-platform at a discount"]', 'A brief professional completion summary', 'A completion summary builds goodwill. Soliciting reviews, disparaging others, and off-platform offers are all prohibited.', 4),
('11111111-0001-0001-0001-000000000007', 'When should you escalate to Sweepr support instead of handling it yourself?', '["When you get a 4-star review", "When a customer is abusive, changes payment terms, or requests out-of-scope work", "Whenever you disagree", "Never"]', 'When a customer is abusive, changes payment terms, or requests out-of-scope work', 'Abuse, payment manipulation, unsafe conditions, and out-of-scope requests exceed a contractor''s role — escalate.', 5);

-- Module 8
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000008', 'The single most important preventive measure against damage claims is:', '["Work slowly", "Photograph pre-existing damage before cleaning each room", "Use only the customer''s products", "Never move furniture"]', 'Photograph pre-existing damage before cleaning each room', 'A timestamped pre-clean photo is your primary defense against false claims. Without it, you have no proof.', 1),
('11111111-0001-0001-0001-000000000008', 'You accidentally break a ceramic vase. What do you do first?', '["Clean up the pieces and hope it goes unnoticed", "Photograph it, message the customer in-app, and file a report within an hour", "Try to glue it", "Mention it verbally at the end"]', 'Photograph it, message the customer in-app, and file a report within an hour', 'Prompt, honest reporting is both ethical and practical. Hiding damage means removal when discovered.', 2),
('11111111-0001-0001-0001-000000000008', 'A customer claims you damaged something you know was already broken. You should:', '["Accept responsibility to keep them happy", "Respond through the claims interface with your dated pre-job photos and facts", "Accuse the customer of lying", "Ignore the claim"]', 'Respond through the claims interface with your dated pre-job photos and facts', 'Present documentation factually without accusation. The trust team reviews both accounts and photo metadata.', 3),
('11111111-0001-0001-0001-000000000008', 'During put-away, how many glasses should you carry at once?', '["As many as possible", "2–3 at a time, held by the body not the rim", "At least 10 to save time", "Stack them all in one trip"]', '2–3 at a time, held by the body not the rim', 'Breakage risk rises with overloaded carries. Extra trips are cheaper than a broken item.', 4),
('11111111-0001-0001-0001-000000000008', 'During an open damage claim, how quickly must you respond to information requests?', '["7 days", "1 month", "Within 48 hours", "You never need to respond"]', 'Within 48 hours', 'Respond within 48 hours during an active claim. Non-responsive cleaners may be suspended pending resolution.', 5);

-- Module 9
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000009', 'How are recent reviews weighted in your quality score?', '["All reviews count equally", "Reviews from the past 30 days count 2x vs. older ones", "Older reviews count more", "Only the last 5 matter"]', 'Reviews from the past 30 days count 2x vs. older ones', 'Recent performance is weighted double, so consistent recent quality recovers your score faster.', 1),
('11111111-0001-0001-0001-000000000009', 'What does Preferred tier require?', '["Quality above 4.0 and reliability above 70", "Quality above 4.5, reliability above 85, and 20+ jobs in 90 days", "Quality above 4.8 and 40+ jobs/month", "Just finishing training"]', 'Quality above 4.5, reliability above 85, and 20+ jobs in 90 days', 'Preferred needs 4.5+ quality, 85+ reliability, and 20+ completed jobs in 90 days. Elite is stricter.', 2),
('11111111-0001-0001-0001-000000000009', 'How much does a no-call/no-show reduce your reliability score?', '["1 point", "3 points", "10 points", "Immediate suspension"]', '10 points', 'A no-call/no-show costs 10 points — far more than a 24-hour cancellation (3 points).', 3),
('11111111-0001-0001-0001-000000000009', 'A family emergency causes you to miss a job. What should you do?', '["Nothing — emergencies are excused automatically", "Contact support within 24 hours, document it, and request a hardship review", "Enter a fake cancellation reason", "Delete your account"]', 'Contact support within 24 hours, document it, and request a hardship review', 'Hardship provisions exist for documented emergencies. Contact support within 24 hours; the impact may be reduced.', 4),
('11111111-0001-0001-0001-000000000009', 'You receive a rating you believe is unfair. What''s the rule on disputes?', '["Dispute anytime you disagree", "Dispute within 7 days when you believe a rating is unfair or inaccurate", "All ratings are final", "Only Elite cleaners can dispute"]', 'Dispute within 7 days when you believe a rating is unfair or inaccurate', 'You have 7 days to dispute. Valid errors may be removed; gaming the system with bad-faith disputes earns warnings.', 5);

-- Module 10
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('11111111-0001-0001-0001-000000000010', 'The app crashes mid-job. What most likely happened to your progress?', '["It''s lost permanently", "It''s saved server-side and reloads when you reopen the app", "You must restart the whole job", "You need to rebook with the customer"]', 'It''s saved server-side and reloads when you reopen the app', 'Progress is saved server-side in real time. A crash just disconnects the client; reopening reconnects your session.', 1),
('11111111-0001-0001-0001-000000000010', 'A payout is 3 business days late beyond the 7-day window. You should:', '["Wait another week", "Contact support through the Help tab with the specific job IDs", "Contact the customer for payment", "File a bank chargeback"]', 'Contact support through the Help tab with the specific job IDs', 'Small delays are normal; at 3+ days late, contact support with job IDs. Never involve the customer in payment issues.', 2),
('11111111-0001-0001-0001-000000000010', 'You can''t access the property and the customer won''t answer. Fastest help is:', '["Email support@sweepr.com", "Post on social media", "The in-app emergency contact, which escalates to a senior agent", "Conference the customer into a support call"]', 'The in-app emergency contact, which escalates to a senior agent', 'The in-app emergency option bypasses the queue for active-job situations and reaches a senior agent fast.', 3),
('11111111-0001-0001-0001-000000000010', 'How should you write a support request for the fastest resolution?', '["Describe it vaguely and let support figure it out", "Include the job ID, the exact issue, what you tried, and screenshots", "Just say the app isn''t working", "Submit several tickets for the same issue"]', 'Include the job ID, the exact issue, what you tried, and screenshots', 'Complete first-message detail eliminates back-and-forth and lets support resolve it immediately.', 4),
('11111111-0001-0001-0001-000000000010', 'Your battery is dying and you didn''t save the address. Best option?', '["Cancel the job", "Use the offline-cached job details in the app, or a screenshot taken before departing", "Call a friend to look it up", "Ring nearby doorbells"]', 'Use the offline-cached job details in the app, or a screenshot taken before departing', 'The app caches addresses offline. Screenshotting before leaving is the recommended backup.', 5);

-- Standard Cleaning quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000001', 'What does a standard clean guarantee that a deep clean is defined by going beyond?', '["Consistent, thorough surface maintenance every visit", "Cleaning inside appliances every visit", "Full cabinet-interior cleaning", "Wall and ceiling cleaning"]', 'Consistent, thorough surface maintenance every visit', 'Standard cleans are maintenance cleans — thorough surface work done consistently. Deep cleaning adds the intensive areas.', 1),
('22222222-0002-0002-0002-000000000001', 'You finish a standard clean well ahead of schedule. What should you do?', '["Leave early and mark complete", "Use the time for finishing touches that drive 5-star reviews", "Start a different job", "Bill for extra time anyway"]', 'Use the time for finishing touches that drive 5-star reviews', 'Spare time is an opportunity for details that earn 5 stars. Never leave early just to pad your rate.', 2),
('22222222-0002-0002-0002-000000000001', 'A customer expects inside-oven cleaning on a standard clean. You should:', '["Do it for free to avoid conflict", "Explain that''s a deep-clean item and offer to prioritize what''s in scope", "Refuse and end the job", "Ignore the request"]', 'Explain that''s a deep-clean item and offer to prioritize what''s in scope', 'Inside appliances are deep-clean scope. Kindly clarify scope and offer to prioritize in-scope work.', 3);

-- Deep Cleaning quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000002', 'How much extra time should you budget for a deep clean vs. a standard clean of the same home?', '["The same amount", "50–75% more", "Always twice as long", "It depends only on bathrooms"]', '50–75% more', 'Deep cleans need 50–75% more time; very neglected homes need even more. Flag scope concerns before starting.', 1),
('22222222-0002-0002-0002-000000000002', 'What should you do with refrigerator shelves and drawers during a deep clean?', '["Wipe them in place", "Remove them, wash in the sink, dry thoroughly, then replace", "Leave them and clean around", "Clean them with oven cleaner"]', 'Remove them, wash in the sink, dry thoroughly, then replace', 'Removing allows complete interior cleaning. Wash with dish soap, dry fully to prevent moisture, and replace.', 2),
('22222222-0002-0002-0002-000000000002', 'Which cleaner is safe for colored grout?', '["Chlorine bleach", "Oxygen-based cleaner like OxiClean", "Any all-purpose cleaner", "Acid-based tile cleaner"]', 'Oxygen-based cleaner like OxiClean', 'Bleach fades grout and acids damage it. Oxygen-based cleaners are safe and effective on most grout.', 3);

-- Move-In/Out quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000003', 'Why is documentation especially important for move-out cleans?', '["To show off your work", "They occur at transition points where landlord-tenant disputes are common and photos may be requested as evidence", "It''s legally required for move-outs", "To help the next cleaner"]', 'They occur at transition points where landlord-tenant disputes are common and photos may be requested as evidence', 'Deposits are at stake. Before/after photos protect you and may be requested in a dispute.', 1),
('22222222-0002-0002-0002-000000000003', 'You find suspected mold in a bathroom during a move-out clean. What should you do?', '["Clean it with bleach and continue", "Stop work on that area, photograph it, and message the customer", "Ignore it and clean around it", "Call the health department"]', 'Stop work on that area, photograph it, and message the customer', 'Mold remediation is outside cleaning scope. Stop, document, and notify the customer — don''t attempt to clean it.', 2),
('22222222-0002-0002-0002-000000000003', 'A landlord is present and asks your opinion on the tenant''s deposit. You should:', '["Share your honest opinion of the home''s condition", "Stay focused on cleaning and avoid discussing the dispute", "Tell them everything you noticed", "Ask the landlord to leave"]', 'Stay focused on cleaning and avoid discussing the dispute', 'Your role is to clean, not testify. Statements could be misrepresented in a landlord-tenant dispute.', 3);

-- Pet Homes quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000004', 'Which product actually eliminates pet odors rather than masking them?', '["Air freshener spray", "Scented candles", "Enzyme-based cleaner", "Baking soda only"]', 'Enzyme-based cleaner', 'Enzyme cleaners break down organic odor compounds. Fresheners and candles only mask odors temporarily.', 1),
('22222222-0002-0002-0002-000000000004', 'Why avoid strong bleach products where pets walk?', '["It damages flooring", "Residual bleach is toxic to dogs and cats", "It doesn''t clean pet areas", "It''s too expensive"]', 'Residual bleach is toxic to dogs and cats', 'Pets lick their paws after walking on treated surfaces; residual bleach can seriously harm them. Use pet-safe products.', 2),
('22222222-0002-0002-0002-000000000004', 'A dog is growling and snapping at you mid-job. What should you do?', '["Calm it with treats", "Stop work, contact the customer, and wait for guidance", "Continue in another room", "Leave without notifying anyone"]', 'Stop work, contact the customer, and wait for guidance', 'An aggressive pet is a safety hazard. Stop, don''t handle the animal, and contact the customer for guidance.', 3);

-- Laundry quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000005', 'When should you start the laundry during a visit?', '["After all cleaning is done", "At the beginning, so it runs while you clean", "Only when asked", "Order doesn''t matter"]', 'At the beginning, so it runs while you clean', 'Starting early maximizes efficiency — cycles run while you do other tasks and you finish put-away near the end.', 1),
('22222222-0002-0002-0002-000000000005', 'You find what looks like a silk blouse in the pile. What should you do?', '["Wash gentle/cold", "Set it aside and note it — it may need special handling or dry cleaning", "Wash normal/warm", "Dry on high heat"]', 'Set it aside and note it — it may need special handling or dry cleaning', 'Silk, wool, and delicates shouldn''t be washed without guidance. Set aside and communicate; damage is costly.', 2),
('22222222-0002-0002-0002-000000000005', 'No instructions are provided. What default water temperature for darks?', '["Hot", "Warm", "Cold — prevents color bleeding and shrinkage", "Any temperature"]', 'Cold — prevents color bleeding and shrinkage', 'Cold is the safe default for darks. When in doubt, cooler water is safer.', 3);
