
-- Dishes quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000006', 'There are crystal wine glasses in the dish pile. What should you do?', '["Dishwasher on gentle", "Hand-wash carefully and dry immediately with a clean cloth", "Skip them entirely", "Scrub hard with a sponge"]', 'Hand-wash carefully and dry immediately with a clean cloth', 'Crystal should always be hand-washed; dishwasher heat and detergent can cloud or crack it over time.', 1),
('22222222-0002-0002-0002-000000000006', 'You break a plate during the dishes add-on. Correct procedure?', '["Throw away the pieces quietly", "Photograph it, message the customer in-app, and file a damage report", "Buy a replacement yourself", "Mention it verbally at the end"]', 'Photograph it, message the customer in-app, and file a damage report', 'Damage reporting is the same for add-ons: document, notify in-app, and file a report.', 2),
('22222222-0002-0002-0002-000000000006', 'You can''t tell where a specific pot belongs. What should you do?', '["Guess the most logical cabinet", "Set it on the counter and note its location in your completion message", "Put it in a random drawer", "Leave it in the drying rack"]', 'Set it on the counter and note its location in your completion message', 'When unsure, leave it visible and communicate. Wrong placement is more disruptive than a noted counter item.', 3);

-- Interior Windows quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000007', 'How should glass cleaner be applied for streak-free results?', '["Sprayed directly on the glass", "Applied to the microfiber cloth, then to the glass", "Sprayed on the squeegee blade", "Applied to paper towels"]', 'Applied to the microfiber cloth, then to the glass', 'Spraying the cloth avoids overspray on frames, sills, and electronics and gives better product control.', 1),
('22222222-0002-0002-0002-000000000007', 'A floor-to-ceiling window needs cleaning but you didn''t bring an extension squeegee. What should you do?', '["Climb on the windowsill", "Document the inaccessible areas and offer to return with proper equipment", "Skip it without noting", "Stand on the customer''s chair"]', 'Document the inaccessible areas and offer to return with proper equipment', 'Never improvise unstable platforms. Document what couldn''t be safely reached and offer a return visit.', 2),
('22222222-0002-0002-0002-000000000007', 'How do you best check windows for streaks?', '["Wipe once more for safety", "View from an angle in natural light", "Run a finger along the glass", "Look head-on under overhead lighting"]', 'View from an angle in natural light', 'A raking angle in natural light reveals streaks that head-on viewing misses.', 3);

-- Organization quiz
INSERT INTO training_quiz_questions (module_id, question, choices, correct_answer, explanation, sort_order) VALUES
('22222222-0002-0002-0002-000000000008', 'You booked a pantry organization, but the bedroom closet is also a mess. What should you do?', '["Organize the closet as a bonus", "Stick to the pantry; note the closet for a possible future booking", "Add the closet to the bill yourself", "Do the closet instead of the pantry"]', 'Stick to the pantry; note the closet for a possible future booking', 'Only organize what''s booked. Touching unrequested areas can hide items. Note opportunities for the future.', 1),
('22222222-0002-0002-0002-000000000008', 'While organizing a pantry you find what looks like trash. What should you do?', '["Throw it away", "Leave it; only discard with explicit customer permission", "Bag it by the front door", "Decide based on your judgment"]', 'Leave it; only discard with explicit customer permission', 'Never discard items without permission — apparent trash may matter to the customer. You organize, you don''t decide.', 2),
('22222222-0002-0002-0002-000000000008', 'A customer asks for organization suggestions. Your role is to:', '["Impose your own system", "Offer options and implement what the customer chooses", "Decline to suggest anything", "Follow a fixed method regardless"]', 'Offer options and implement what the customer chooses', 'You assist the customer''s vision. Offer professional options, then implement their decision — their system is the right one.', 3);
