// swift-tools-version: 5.9
//
// Copyright © 2026–Present ClearKey Solutions, LLC.
// All Rights Reserved.
//
// Proprietary and Confidential.
//
// Unauthorized copying, modification, disclosure,
// distribution, reverse engineering, or use is prohibited.
//
import PackageDescription

// Sweepr — customer app. SKIP dual-platform SwiftPM package.
//
// The iOS app target lives in the Xcode project under Darwin/ (generated by
// `skip init` / checked in), which links this `Sweepr` library. `skip export`
// transpiles this same library into the Android/Compose app module.
let package = Package(
    name: "Sweepr",
    defaultLocalization: "en",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "Sweepr", targets: ["Sweepr"]),
    ],
    dependencies: [
        .package(path: "../SweeprKit"),
        .package(url: "https://source.skip.tools/skip.git", from: "1.2.0"),
        .package(url: "https://source.skip.tools/skip-ui.git", from: "1.0.0"),
        .package(url: "https://source.skip.tools/skip-foundation.git", from: "1.0.0"),
        .package(url: "https://source.skip.tools/skip-model.git", from: "1.0.0"),
    ],
    targets: [
        .target(
            name: "Sweepr",
            dependencies: [
                .product(name: "SweeprKit", package: "SweeprKit"),
                .product(name: "SkipUI", package: "skip-ui"),
                .product(name: "SkipFoundation", package: "skip-foundation"),
                .product(name: "SkipModel", package: "skip-model"),
            ],
            resources: [.process("Resources")],
            plugins: [.plugin(name: "skipstone", package: "skip")]
        ),
    ]
)
