#!/usr/bin/env node
/**
 * Generates packages/db/schema.sql — a single, idempotent, consolidated
 * schema you can paste into the Neon SQL editor / cloud shell to guarantee
 * every table, column, type, index and constraint exists.
 *
 * It concatenates the *structural* migrations (skipping the 008* content
 * seeds) in order and rewrites statements to be safely re-runnable:
 *   - CREATE TABLE            -> CREATE TABLE IF NOT EXISTS
 *   - CREATE INDEX            -> CREATE INDEX IF NOT EXISTS
 *   - CREATE TYPE … AS ENUM   -> wrapped in a duplicate_object-safe DO block
 *   - ALTER … ADD COLUMN      -> ADD COLUMN IF NOT EXISTS
 *   - ALTER … ADD CONSTRAINT  -> wrapped in a duplicate_object-safe DO block
 *
 * Run:  node packages/db/build-schema.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIG_DIR = join(__dirname, "src", "migrations");

const files = readdirSync(MIG_DIR)
  .filter((f) => f.endsWith(".sql"))
  .filter((f) => /^\d{3}/.test(f)) // numbered migrations only (skip neon-ensure.sql etc.)
  .filter((f) => !/^008/.test(f)) // skip training content seeds
  .sort();

function idempotent(sql) {
  // CREATE TABLE foo  ->  CREATE TABLE IF NOT EXISTS foo
  sql = sql.replace(/CREATE TABLE (?!IF NOT EXISTS)/gi, "CREATE TABLE IF NOT EXISTS ");
  // CREATE [UNIQUE] INDEX foo -> ... IF NOT EXISTS foo
  sql = sql.replace(/CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)/gi, (_m, u) => `CREATE ${u ?? ""}INDEX IF NOT EXISTS `);
  // ALTER TABLE x ADD COLUMN y -> ADD COLUMN IF NOT EXISTS y
  sql = sql.replace(/ADD COLUMN (?!IF NOT EXISTS)/gi, "ADD COLUMN IF NOT EXISTS ");

  // CREATE TYPE name AS ENUM ( ... );  ->  DO block guarded against re-run.
  sql = sql.replace(
    /CREATE TYPE\s+(\w+)\s+AS\s+ENUM\s*\(([\s\S]*?)\)\s*;/gi,
    (_m, name, body) =>
      `DO $$ BEGIN\n  CREATE TYPE ${name} AS ENUM (${body});\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$;`
  );

  // ALTER TABLE t ADD CONSTRAINT c ... ;  ->  guarded DO block.
  // (Postgres has no ADD CONSTRAINT IF NOT EXISTS.) Also strip any invalid
  // "ADD CONSTRAINT IF NOT EXISTS" that slipped into a migration.
  sql = sql.replace(/ADD CONSTRAINT IF NOT EXISTS/gi, "ADD CONSTRAINT");
  sql = sql.replace(
    /ALTER TABLE\s+(\w+)\s+ADD CONSTRAINT\s+(\w+)\s+([\s\S]*?);/gi,
    (_m, table, cons, def) =>
      `DO $$ BEGIN\n  ALTER TABLE ${table} ADD CONSTRAINT ${cons} ${def.trim()};\nEXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL;\nEND $$;`
  );

  return sql;
}

let out = `-- ============================================================================
-- sweepr — CONSOLIDATED SCHEMA (generated by build-schema.mjs)
--
-- Safe to run repeatedly against any Neon database. It ensures every table,
-- column, type, index and constraint the application expects is present.
-- Paste the whole file into the Neon SQL editor and run it.
--
-- This file is GENERATED. Do not edit by hand — edit the migrations in
-- src/migrations/ and re-run: node packages/db/build-schema.mjs
--
-- Source migrations: ${files.join(", ")}
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

`;

for (const f of files) {
  const raw = readFileSync(join(MIG_DIR, f), "utf8");
  out += `\n-- ─────────────────────────────────────────────────────────────────────────\n-- ${f}\n-- ─────────────────────────────────────────────────────────────────────────\n`;
  out += idempotent(raw).trimEnd() + "\n";
}

writeFileSync(join(__dirname, "schema.sql"), out);
console.log(`Wrote schema.sql from ${files.length} migrations (${out.length} bytes).`);
